# Generated by Django 3.2.9 on 2022-01-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_alter_basketitem_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketitem',
            old_name='qty',
            new_name='quantity',
        ),
    ]
