# Generated by Django 3.2.9 on 2022-01-12 09:56

import authapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210201_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='activation_key',
            field=models.CharField(max_length=128, null=True, verbose_name='ключ активации'),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='activation_key_expiry',
            field=models.DateTimeField(default=authapp.models.get_expiry_date, max_length=128, verbose_name='активация истекает'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
